name: action_proxy_direct.yaml
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook_archiveteam
jobs:
  Fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    strategy:
      matrix:
        shard: [0,1,2,3,4,5,6,7,8,9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
      - name: hola-proxy | xsv
        run: |
          sudo snap install hola-proxy
          XSV_VERSION=$(curl -s "https://api.github.com/repos/BurntSushi/xsv/releases/latest" | grep -Po '"tag_name": "\K[0-9.]+')
          curl -Lo xsv.tar.gz "https://github.com/BurntSushi/xsv/releases/latest/download/xsv-${XSV_VERSION}-x86_64-unknown-linux-musl.tar.gz"
          sudo tar xf xsv.tar.gz -C /usr/local/bin
          rm -rf xsv.tar.gz
      - name: script_generate_proxylist_hola
        run: |
          #bash script_generate_proxylist_hola.sh
          #cat proxies_hola.txt
      - name: install mubeng
        run: |
          #export PATH=${PATH}:`go env GOPATH`/bin
          #go install ktbs.dev/mubeng/cmd/mubeng@latest
      - name: mubeng
        run: |
         # export PATH=${PATH}:`go env GOPATH`/bin
          #mubeng -f proxies_hola.txt -a '127.0.0.1:44444' &
      - name: Run Proxy
        run: |
          bash code.sh ${{ matrix.shard }} 
