name: action_proxy_direct.yaml
on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook_archiveteam
jobs:
  Fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    strategy:
      matrix:
        shard: [0,1,2,3,4,5,6,7,8,9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
      - name: Run Proxy
        run: |
          bash code.sh ${{ matrix.shard }} 
